#!/bin/bash
grep -i "^[A-Z]" /etc/ssh/sshd_config#!/bin/bash
grep -i "^[A-Z]" /etc/ssh/sshd_config#!/bin/bash
grep -i "^[A-Z]" /etc/ssh/sshd_config#!/bin/bash
grep -i "^[A-Z]" /etc/ssh/sshd_config#!/bin/bash
grep -i "^[A-Z]" /etc/ssh/sshd_config#!/bin/bash
grep -i "^[A-Z]" /etc/ssh/sshd_config
